-- SCHEMA: NOT USED
-- Table: trailers
-- Stores the information about the trailers in the fleet
CREATE TABLE IF NOT EXISTS trailers (
    Trailer_ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    -- Trailer_UUID uuid DEFAULT gen_random_uuid(),
    VIN TEXT PRIMARY KEY,
    IMEI BIGINT NOT NULL,
    Make TEXT NULL,
    Model TEXT NULL,
    Active BOOLEAN NOT NULL,
    Track_Width_T REAL NOT NULL,
    Spring_Lat_Spacing REAL NOT NULL,
    Roll_Centre_H REAL NOT NULL,
    Kingpin_To_Axle_1 REAL NOT NULL,
    Axle_Spacing_1_2 REAL NOT NULL,
    Axle_Spacing_2_3 REAL NOT NULL,
    Unsprung_Mass_Axle_1 REAL NOT NULL,
    Unsprung_Mass_Axle_2 REAL NOT NULL,
    Unsprung_Mass_Axle_3 REAL NOT NULL,
    Sprung_Mass_Trailer REAL NOT NULL,
    Total_Mass_Trailer REAL NOT NULL,
    Suspension_Ratio REAL NOT NULL,
    Sprung_CG_Height REAL NOT NULL,
    CG_to_Axle_1 REAL NOT NULL,
    CG_to_Axle_2 REAL NOT NULL,
    CG_to_Axle_3 REAL NOT NULL
);

-- Table: trailer_input
-- Stores the incoming data from trailers
CREATE TABLE IF NOT EXISTS trailer_input (
    "time" TIMESTAMPTZ NOT NULL,
    ServerTime TIMESTAMPTZ NOT NULL,
    IMEI BIGINT NOT NULL,
    OdoTotal real NOT NULL,
    OdoTrip real NOT NULL,
    Altitude INT NOT NULL,
    Speed INT NOT NULL,
    SpeedSat INT NOT NULL,
    Latitude real NULL,
    Longitude real NULL,
    Angle INT NOT NULL,
    IgnitionStatus TEXT NOT NULL,
    Movement TEXT NOT NULL,
    DLAxle1LAX real NOT NULL,
    DLAxle1LAY real NOT NULL,
    DLAxle1LAZ real NOT NULL,
    DLAxle1LGX real NOT NULL,
    DLAxle1LGY real NOT NULL,
    DLAxle1LGZ real NOT NULL,
    DLAxle1LRMSZ real NOT NULL,
    DLAxle1LZMIN real NOT NULL,
    DLAxle1LZMAX real NOT NULL,
    DLAxle1RAX real NOT NULL,
    DLAxle1RAY real NOT NULL,
    DLAxle1RAZ real NOT NULL,
    DLAxle1RGX real NOT NULL,
    DLAxle1RGY real NOT NULL,
    DLAxle1RGZ real NOT NULL,
    DLAxle1RRMSZ real NOT NULL,
    DLAxle1RZMIN real NOT NULL,
    DLAxle1RZMAX real NOT NULL,
    DLAxle2LAX real NOT NULL,
    DLAxle2LAY real NOT NULL,
    DLAxle2LAZ real NOT NULL,
    DLAxle2LGX real NOT NULL,
    DLAxle2LGY real NOT NULL,
    DLAxle2LGZ real NOT NULL,
    DLAxle2LRMSZ real NOT NULL,
    DLAxle2LZMIN real NOT NULL,
    DLAxle2LZMAX real NOT NULL,
    DLAxle2RAX real NOT NULL,
    DLAxle2RAY real NOT NULL,
    DLAxle2RAZ real NOT NULL,
    DLAxle2RGX real NOT NULL,
    DLAxle2RGY real NOT NULL,
    DLAxle2RGZ real NOT NULL,
    DLAxle2RRMSZ real NOT NULL,
    DLAxle2RZMIN real NOT NULL,
    DLAxle2RZMAX real NOT NULL,
    DLKingpinAX real NOT NULL,
    DLKingpinAY real NOT NULL,
    DLKingpinAZ real NOT NULL,
    DLKingpinGX real NOT NULL,
    DLKingpinGY real NOT NULL,
    DLKingpinGZ real NOT NULL,
    DLKingpinRMSZ real NOT NULL,
    DLKingpinZMIN real NOT NULL,
    DLKingpinZMAX real NOT NULL,
    DLSpare1AX real NOT NULL,
    DLSpare1AY real NOT NULL,
    DLSpare1AZ real NOT NULL,
    DLSpare1GX real NOT NULL,
    DLSpare1GY real NOT NULL,
    DLSpare1GZ real NOT NULL,
    DLSpare1RMSZ real NOT NULL,
    DLSpare1ZMIN real NOT NULL,
    DLSpare1ZMAX real NOT NULL,
    DLSpare2AX real NOT NULL,
    DLSpare2AY real NOT NULL,
    DLSpare2AZ real NOT NULL,
    DLSpare2GX real NOT NULL,
    DLSpare2GY real NOT NULL,
    DLSpare2GZ real NOT NULL,
    DLSpare2RMSZ real NOT NULL,
    DLSpare2ZMIN real NOT NULL,
    DLSpare2ZMAX real NOT NULL,
    DLSpecialAX real NOT NULL,
    DLSpecialAY real NOT NULL,
    DLSpecialAZ real NOT NULL,
    DLSpecialGX real NOT NULL,
    DLSpecialGY real NOT NULL,
    DLSpecialGZ real NOT NULL,
    DLSpecialRMSZ real NOT NULL,
    DLSpecialZMIN real NOT NULL,
    DLSpecialZMAX real NOT NULL,
    FMCAxisX real NOT NULL,
    FMCAxisY real NOT NULL,
    FMCAxisZ real NOT NULL,
    SystemPressure real NOT NULL,
    DemandPressure real NOT NULL,
    EBSPressure real NOT NULL,
    BrakeApplicationPressureH real NOT NULL,
    BrakeApplicationPressureL real NOT NULL,
    VIN TEXT REFERENCES trailers (VIN),
    TrailerLoadPercent int NOT NULL,
    VDCActive TEXT NULL,
    WheelBasedVehSpeed real NOT NULL,
    ABPresLHRear real NOT NULL,
    ABPresLHMID real NOT NULL,
    ABPresLHFront real NOT NULL,
    ABPresRHFront real NOT NULL,
    ABPresRHMID real NOT NULL,
    ABPresRHRear real NOT NULL,
    AxleLoadLHRear real NOT NULL,
    AxleLoadLHFront real NOT NULL,
    AxleLoadRHFront real NOT NULL,
    AxleLoadRHRear real NOT NULL,
    AxleLoadLHCentre real NOT NULL,
    AxleLoadRHCentre real NOT NULL,
    SatellitesCount int NULL,
    GNSSStatus TEXT NULL,
    GSMSignal int NULL,
    GNSSPdop real NOT NULL,
    GNSSHdop real NOT NULL,
    DataMode TEXT NULL,
    VoltageTrailer real NOT NULL,
    VoltageBattery real NOT NULL,
    CurrentBattery real NOT NULL,
    Event int NULL,
    Priority int NULL,
    NumOfRecords int NULL
);

-- Table: trailer_load
-- Stores calculated load data from trailer input data
CREATE TABLE IF NOT EXISTS trailer_loads (
    "time" TIMESTAMPTZ NOT NULL,
    VIN TEXT REFERENCES trailers (VIN),
    StatusLoaded TEXT,
    FAirAx1LN real NOT NULL,
    FAirAx1RN real NOT NULL,
    FAirAx2LN real NOT NULL,
    FAirAx2RN real NOT NULL,
    FAirAx3LN real NOT NULL,
    FAirAx3RN real NOT NULL,
    KAx1LNPerm real NOT NULL,
	KAx1RNPerm real NOT NULL,
	KAx2LNPerm real NOT NULL,
	KAx2RNPerm real NOT NULL,
	KAx3LNPerm real NOT NULL,
	KAx3RNPerm real NOT NULL,
    FInertiaAx1LN real NOT NULL,
    FInertiaAx1RN real NOT NULL,
    FFInertiaAx2LN real NOT NULL,
    FInertiaAx2RN real NOT NULL,
    FInertiaAx3LN real NOT NULL,
    FInertiaAx3RN real NOT NULL,
    XAx1Lm real NOT NULL,
	XAx1Rm real NOT NULL,
	XAx2Lm real NOT NULL,
	XAx2Rm real NOT NULL,
	XAx3Lm real NOT NULL,
	XAx3Rm real NOT NULL,
    DeltaT real NOT NULL,
    XDotAx1LMps real NOT NULL,
    XDotAx1RMps real NOT NULL,
    XDotAx2LMps real NOT NULL,
    XDotAx2RMps real NOT NULL,
    XDotAx3LMps real NOT NULL,
    XDotAx3RMps real NOT NULL,
    XDotFAx1LMps real NOT NULL,
    XDotFAx1RMps real NOT NULL,
    XDotFAx2LMps real NOT NULL,
    XDotFAx2RMps real NOT NULL,
    XDotFAx3LMps real NOT NULL,
    XDotFAx3RMps real NOT NULL,
    FdAx1LN real NOT NULL,
    FdAx1RN real NOT NULL,
    FdAx2LN real NOT NULL,
    FdAx2RN real NOT NULL,
    FdAx3LN real NOT NULL,
    FdAx3RN real NOT NULL,
    FzAx1LN real NOT NULL,
    FzAx1RN real NOT NULL,
    FzAx2LN real NOT NULL,
    FzAx2RN real NOT NULL,
    FzAx3LN real NOT NULL,
    FzAx3RN real NOT NULL,
    FzTotalN real NOT NULL,
    FzLTotalN real NOT NULL,
    FzRTotalN real NOT NULL,
    FzAx1TotalN real NOT NULL,
    FzAx2TotalN real NOT NULL,
    FzAx3TotalN real NOT NULL,
    FzAx1AbsLN real NOT NULL,
    FzAx1AbsRN real NOT NULL,
    FzAx2AbsLN real NOT NULL,
    FzAx2AbsRN real NOT NULL,
    FzAx3AbsLN real NOT NULL,
    FzAx3AbsRN real NOT NULL,
    LTRGroup real NOT NULL,
    DeltaFzLatAx1 real NOT NULL,
    DeltaFzLatAx2 real NOT NULL,
    DeltaFzLatAx3 real NOT NULL,
    UMps real NOT NULL,
    RKpRps real NOT NULL,
    AyG real NOT NULL,
    MRollNm real NOT NULL,
    BPAxBar real NOT NULL,
    BPAx1LBar real NOT NULL,
    BPAx1RBar real NOT NULL,
    BPAx2LBar real NOT NULL,
    BPAx2RBar real NOT NULL,
    BPAx3LBar real NOT NULL,
    BPAx3RBar real NOT NULL,
    TWheelAx1L real NOT NULL,
    TWheelAx1R real NOT NULL,
    TWheelAx2L real NOT NULL,
    TWheelAx2R real NOT NULL,
    TWheelAx3L real NOT NULL,
    TWheelAx3R real NOT NULL,
    FxBrakeAx1L real NOT NULL,
    FxBrakeAx1R real NOT NULL,
    FxBrakeAx2L real NOT NULL,
    FxBrakeAx2R real NOT NULL,
    FxBrakeAx3L real NOT NULL,
    FxBrakeAx3R real NOT NULL,
    FxBrakeAx1Total real NOT NULL,
    FxBrakeAx2Total real NOT NULL,
    FxBrakeAx3Total real NOT NULL,
    FxBrakeTotal real NOT NULL,
    BetaBodyRad real NOT NULL,
    AlphaAx1LRad real NOT NULL,
    AlphaAx1RRad real NOT NULL,
    AlphaAx2LRad real NOT NULL,
    AlphaAx2RRad real NOT NULL,
    AlphaAx3LRad real NOT NULL,
    AlphaAx3RRad real NOT NULL,
    FyAx1LN real NOT NULL,
    FyAx1RN real NOT NULL,
    FyAx2LN real NOT NULL,
    FyAx2RN real NOT NULL,
    FyAx3LN real NOT NULL,
    FyAx3RN real NOT NULL,
    FyTotalN real NOT NULL,
    MzYawNm real NOT NULL,
    MassEffective real NOT NULL,
    FxKingpinN real NOT NULL,
    FyKingpinNreal real NOT NULL,
    FzKingpinNreal real NOT NULL,
    MassEstRearkg real NOT NULL,
    RollTransferGain real NOT NULL,
    DeflectBiasAx1 real NOT NULL,
    DeflectBiasAx2 real NOT NULL,
    DeflectBiasAx3 real NOT NULL
);

-- Timescaledb create a hypertable
SELECT create_hypertable('trailer_input', by_range('time'));
-- CREATE INDEX idx_time ON trailer_input (time DESC)
CREATE INDEX idx_time_vin ON trailer_input (VIN, time DESC)

-- SELECT create_hypertable('trailer_loads', by_range('time'));
-- CREATE INDEX idx_time ON trailer_loads (time DESC)
-- CREATE INDEX idx_time_vin ON trailer_loads (VIN, "time" DESC)

-- Temporary data
-- 